### ISSUE TITLE
Run from an npm install

### ISSUE THREAD

**Issue by grtjn** [lonhutt/mlrepl#1]
Would be nice if you could just do `npm install mlrepl`, and run the command `mlrepl` after that to get going. I was also wondering if you could use mlrepl to execute local .sjs scripts against a server..

**Comment by lonhutt** [comment]
I've definitely got that on my list.. I was also strongly considering using this

https://www.npmjs.com/package/nar

to roll the whole thing up so it can be executed as it's own self-contained binary..

**Comment by grtjn** [comment]
Not sure why you closed this. You only need to do an npm publish to get this published on the npm registry, and then you can do npm install mlrepl (from anywhere). To install the mlrepl command as a global command-line, you would run npm install -g mlrepl.

If you publish this on npm, people wouldn't have to git clone this first, go in and run the npm install from there. They could run npm install mlrepl (-g) to get things installed appropriately..

**Comment by lonhutt** [comment]
sorry for the confusion before.. i had it stuck in my head that all i need todo was get the 'npm install -g' working on; i completely spaced getting it registered on NPM.

It is there now: https://www.npmjs.com/package/mlrepl
