### ISSUE TITLE
mlrepl is not using host from .mlreplrc

### ISSUE THREAD

**Issue by mstellwa** [lonhutt/mlrepl#3]
The init function does not get host from the config file:
  init: function(){
    this.fetchConfig(true);
    this.fetchCompletionGroups();
    var config = getConfig();
    this.user = (config.username) ? config.username : this.user;
    this.password = (config.password) ? config.password : this.password;
    this.database = (config.database) ? config.database : this.database;
    this.port = (config.port) ? config.port : this.port;
  },

Also for some reason  the fetchConfig: function(init){ ... is using localhost even if this.host  = (config.host) ? config.host : this.host; is added to the init: function(){

**Comment by lonhutt** [comment]
good catch...

i jammed this things out when i ported everything from a node server to a native ML server. No one has mentioned it since so far i guess everyone has been running against localhost. I'll get this updated as soon as i can.

**Comment by lonhutt** [comment]
just pushed a fix that should take care of the issue.. if you're executing an 'npm install -g' you'll want to change the .mlreplrc file in the root project folder (part of the install process is to copy that file into your home directory)
